import type { Metadata } from "next";
import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/navbar";
import Layout from "@/components/layout";

import ModalProvider from "@/providers/ModalProvider";

const inter = Inter({ subsets: ["latin"], variable: "--body-font" });

export const metadata: Metadata = {
  title: "AniLearn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" id="top">
      <body
        className={`${inter.variable} bg-background font-body text-foreground`}
      >
        <Layout>
          <ModalProvider />
          {/* <TopBanner /> */}
          <Navbar />
          {children}
          {/* <Footer /> */}
        </Layout>
      </body>
    </html>
  );
}
