import Buttons from "@/components/Buttons";
import { userSelector } from "@/redux/user/user.selector";
import Head from "next/head";
import { useSelector } from "react-redux";

export default function Home() {
  const user = useSelector(userSelector);
  console.log(user);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{/* <Buttons /> */}</main>
    </>
  );
}
