import Head from "next/head";

import { DM_Sans } from "@next/font/google";
import Hero from "@/components/Hero";
import Information from "@/components/Information";
import Buying from "@/components/Buying";

const dm_sans = DM_Sans({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={dm_sans.className}>
        <Hero />
        <Information />
        <Buying />
      </main>
    </>
  );
}
