// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  "border-radius": {
    name: "border-radius",
    component: React.lazy(() => import("@/registry/css/border-radius.tsx")),
  },
  "flex-position": {
    name: "flex-position",
    component: React.lazy(() => import("@/registry/css/flex-position.tsx")),
  },
  "inputs-checkbox": {
    name: "inputs-checkbox",
    component: React.lazy(() => import("@/registry/html/inputs/checkbox.tsx")),
  },
  "inputs-email": {
    name: "inputs-email",
    component: React.lazy(() => import("@/registry/html/inputs/email.tsx")),
  },
  "inputs-file": {
    name: "inputs-file",
    component: React.lazy(() => import("@/registry/html/inputs/file.tsx")),
  },
  "inputs-password": {
    name: "inputs-password",
    component: React.lazy(() => import("@/registry/html/inputs/password.tsx")),
  },
  "inputs-radio": {
    name: "inputs-radio",
    component: React.lazy(() => import("@/registry/html/inputs/radio.tsx")),
  },
  "inputs-reset": {
    name: "inputs-reset",
    component: React.lazy(() => import("@/registry/html/inputs/reset.tsx")),
  },
  "inputs-search": {
    name: "inputs-search",
    component: React.lazy(() => import("@/registry/html/inputs/search.tsx")),
  },
  "inputs-submit": {
    name: "inputs-submit",
    component: React.lazy(() => import("@/registry/html/inputs/submit.tsx")),
  },
  "inputs-text": {
    name: "inputs-text",
    component: React.lazy(() => import("@/registry/html/inputs/text.tsx")),
  },
  "inputs-url": {
    name: "inputs-url",
    component: React.lazy(() => import("@/registry/html/inputs/url.tsx")),
  },
  "my-open-graph": {
    name: "my-open-graph",
    component: React.lazy(() => import("@/registry/html/my-open-graph.tsx")),
  },
  "open-graph": {
    name: "open-graph",
    component: React.lazy(() => import("@/registry/html/open-graph.tsx")),
  },
};
