/* eslint-disable */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  "border-radius": {
    name: "border-radius",
    component: React.lazy(() => import("@/registry/css/border-radius.tsx")),
  },
  "flex-position": {
    name: "flex-position",
    component: React.lazy(() => import("@/registry/css/flex-position.tsx")),
  },
  "my-open-graph": {
    name: "my-open-graph",
    component: React.lazy(() => import("@/registry/html/my-open-graph.tsx")),
  },
  "open-graph": {
    name: "open-graph",
    component: React.lazy(() => import("@/registry/html/open-graph.tsx")),
  },
};
/* eslint-enable */
