// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  "border-radius-index": {
    name: "border-radius-index",
    component: React.lazy(
      () => import("@/registry/css/border-radius/index.tsx")
    ),
  },
  "border-radius-whole": {
    name: "border-radius-whole",
    component: React.lazy(
      () => import("@/registry/css/border-radius/whole.tsx")
    ),
  },
  "center-flexbox": {
    name: "center-flexbox",
    component: React.lazy(() => import("@/registry/css/center/flexbox.tsx")),
  },
  "center-gridbox-2": {
    name: "center-gridbox-2",
    component: React.lazy(() => import("@/registry/css/center/gridbox-2.tsx")),
  },
  "center-gridbox": {
    name: "center-gridbox",
    component: React.lazy(() => import("@/registry/css/center/gridbox.tsx")),
  },
  "center-margin": {
    name: "center-margin",
    component: React.lazy(() => import("@/registry/css/center/margin.tsx")),
  },
  "center-position": {
    name: "center-position",
    component: React.lazy(() => import("@/registry/css/center/position.tsx")),
  },
  cursor: {
    name: "cursor",
    component: React.lazy(() => import("@/registry/css/cursor.tsx")),
  },
  "flex-position": {
    name: "flex-position",
    component: React.lazy(() => import("@/registry/css/flex-position.tsx")),
  },
  "flexbox-align-content": {
    name: "flexbox-align-content",
    component: React.lazy(
      () => import("@/registry/css/flexbox/align-content.tsx")
    ),
  },
  "flexbox-align-items": {
    name: "flexbox-align-items",
    component: React.lazy(
      () => import("@/registry/css/flexbox/align-items.tsx")
    ),
  },
  "flexbox-align-self": {
    name: "flexbox-align-self",
    component: React.lazy(
      () => import("@/registry/css/flexbox/align-self.tsx")
    ),
  },
  "flexbox-justify-content": {
    name: "flexbox-justify-content",
    component: React.lazy(
      () => import("@/registry/css/flexbox/justify-content.tsx")
    ),
  },
  "transform-rotate-x": {
    name: "transform-rotate-x",
    component: React.lazy(
      () => import("@/registry/css/transform/rotate-x.tsx")
    ),
  },
  "transform-rotate-y": {
    name: "transform-rotate-y",
    component: React.lazy(
      () => import("@/registry/css/transform/rotate-y.tsx")
    ),
  },
  "transform-rotate": {
    name: "transform-rotate",
    component: React.lazy(() => import("@/registry/css/transform/rotate.tsx")),
  },
  "transform-scale-x": {
    name: "transform-scale-x",
    component: React.lazy(() => import("@/registry/css/transform/scale-x.tsx")),
  },
  "transform-scale-y": {
    name: "transform-scale-y",
    component: React.lazy(() => import("@/registry/css/transform/scale-y.tsx")),
  },
  "transform-scale": {
    name: "transform-scale",
    component: React.lazy(() => import("@/registry/css/transform/scale.tsx")),
  },
  "transform-setting": {
    name: "transform-setting",
    component: React.lazy(() => import("@/registry/css/transform/setting.tsx")),
  },
  "transform-skew-x": {
    name: "transform-skew-x",
    component: React.lazy(() => import("@/registry/css/transform/skew-x.tsx")),
  },
  "transform-skew-y": {
    name: "transform-skew-y",
    component: React.lazy(() => import("@/registry/css/transform/skew-y.tsx")),
  },
  "transform-skew": {
    name: "transform-skew",
    component: React.lazy(() => import("@/registry/css/transform/skew.tsx")),
  },
  "transform-translate": {
    name: "transform-translate",
    component: React.lazy(
      () => import("@/registry/css/transform/translate.tsx")
    ),
  },
  "inputs-checkbox": {
    name: "inputs-checkbox",
    component: React.lazy(() => import("@/registry/html/inputs/checkbox.tsx")),
  },
  "inputs-email": {
    name: "inputs-email",
    component: React.lazy(() => import("@/registry/html/inputs/email.tsx")),
  },
  "inputs-file": {
    name: "inputs-file",
    component: React.lazy(() => import("@/registry/html/inputs/file.tsx")),
  },
  "inputs-password": {
    name: "inputs-password",
    component: React.lazy(() => import("@/registry/html/inputs/password.tsx")),
  },
  "inputs-radio": {
    name: "inputs-radio",
    component: React.lazy(() => import("@/registry/html/inputs/radio.tsx")),
  },
  "inputs-reset": {
    name: "inputs-reset",
    component: React.lazy(() => import("@/registry/html/inputs/reset.tsx")),
  },
  "inputs-search": {
    name: "inputs-search",
    component: React.lazy(() => import("@/registry/html/inputs/search.tsx")),
  },
  "inputs-submit": {
    name: "inputs-submit",
    component: React.lazy(() => import("@/registry/html/inputs/submit.tsx")),
  },
  "inputs-text": {
    name: "inputs-text",
    component: React.lazy(() => import("@/registry/html/inputs/text.tsx")),
  },
  "inputs-url": {
    name: "inputs-url",
    component: React.lazy(() => import("@/registry/html/inputs/url.tsx")),
  },
  "my-open-graph": {
    name: "my-open-graph",
    component: React.lazy(() => import("@/registry/html/my-open-graph.tsx")),
  },
  "open-graph": {
    name: "open-graph",
    component: React.lazy(() => import("@/registry/html/open-graph.tsx")),
  },
};
